# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'javViewer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for javViewer
  pod 'SDWebImage'
	pod 'Masonry'
	pod 'MJRefresh'
	pod 'JSONModel'
	pod 'Ono'
	pod 'AFNetworking'
	pod 'FMDB'
	pod 'ReactiveCocoa'

end
